FROM golang:1.24.4


WORKDIR /kokaq/server

COPY core /kokaq/core
COPY protocol /kokaq/protocol
COPY server /kokaq/server
COPY server/go.dev.work /kokaq/go.work
WORKDIR /kokaq/server

# Optional default ports
ENV PORT=9001
ENV SHARD_MANAGER_ADDRESS=control-plane:8999
ENV ROOT_DIRECTORY=/kokaq/bin

# Expose only default port, can be overridden at runtime
EXPOSE ${PORT}

CMD ["go", "run", "./cmd/dataplane/main.go"]
