package proxy

const (
	// QUEUE_SERVICE_MESSAGE_CONTENT_ETCDENDPOINTS_ENV     = "QUEUE_SERVICE_MESSAGE_CONTENT_ETCDENDPOINTS_ENV"
	// QUEUE_SERVICE_MESSAGE_CONTENT_ETCDTIMEOUT_ENV       = "QUEUE_SERVICE_MESSAGE_CONTENT_ETCDTIMEOUT_ENV"
	// QUEUE_SERVICE_POD_MAPPING_ETCDENDPOINTS_ENV         = "QUEUE_SERVICE_POD_MAPPING_ETCDENDPOINTS_ENV"
	// QUEUE_SERVICE_POD_MAPPING_ETCDTIMEOUT_ENV           = "QUEUE_SERVICE_POD_MAPPING_ETCDTIMEOUT_ENV"
	// QUEUE_SERVICE_STORAGE_SERVICE_TIMEOUT_ENV           = "QUEUE_SERVICE_STORAGE_SERVICE_TIMEOUT_ENV"
	// QUEUE_SERVICE_STORAGE_SERVICE_POD_FETCH_TIMEOUT_ENV = "QUEUE_SERVICE_STORAGE_SERVICE_POD_FETCH_TIMEOUT_ENV"
	// QUEUE_SERVICE_STORAGE_SERVICE_RETRIES_ENV           = "QUEUE_SERVICE_STORAGE_SERVICE_RETRIES_ENV"

	QUEUE_SERVICE_MESSAGE_CONTENT_ETCDENDPOINTS_DEFAULT     = "172.202.147.86:2379"
	QUEUE_SERVICE_MESSAGE_CONTENT_ETCDTIMEOUT_DEFAULT       = 10
	QUEUE_SERVICE_POD_MAPPING_ETCDENDPOINTS_DEFAULT         = "172.202.147.86:2379"
	QUEUE_SERVICE_POD_MAPPING_ETCDTIMEOUT_DEFAULT           = 10
	QUEUE_SERVICE_STORAGE_SERVICE_TIMEOUT_DEFAULT           = 10
	QUEUE_SERVICE_STORAGE_SERVICE_POD_FETCH_TIMEOUT_DEFAULT = 3600
	QUEUE_SERVICE_API_TCP_TIMEOUT_IN_SECONDS_DEFAULT        = 10
	QUEUE_SERVICE_STORAGE_SERVICE_RETRIES_DEFAULT           = 3

	QUEUE_SERVICE_STORAGE_SERVICE_PODS_CACHE_KEY = "QUEUE_SERVICE_STORAGE_SERVICE_PODS_CACHE_KEY"
	QUEUE_SERVICE_STORAGE_SERVICE_POD_LABEL      = "app=prefq-storage-service"

	TARGET_PORT_CREATE = "9944"
	TARGET_PORT_DELETE = "9944"
	TARGET_PORT_PEEK   = "9944"
	TARGET_PORT_POP    = "9944"
	TARGET_PORT_PUSH   = "9944"
	CREATE_RETRIES     = 3
)
